DEBUG = -g
OPT = -O1 -pg -g3 -m32 -D_16BPP -DSOFTWARE_SCALING
LINKER = 
SDLDIR = 
CFLAGS = -Iinclude -Wall $(shell sdl-config --cflags) -DLINUX $(OPT)
SDLLIB = $(shell sdl-config --libs)
LIBS = $(SDLLIB)
O=.o
A=
EXE=.linux
CC = gcc
COMPILE = -c
LINK = -o 

include makefile.rule
